name: food_delivery
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.5+3
  flutter_typeahead: ^4.0.0
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.1.1
  flutter_otp_text_field: ^1.0.1
  flutter_slidable: ^2.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  hive: ^2.2.3
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  localize: ^0.0.4
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.4.4
  firebase_database: ^9.1.1
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Viga
      fonts:
        - asset: assets/fonts/Viga-Regular.ttf
          style: normal
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          style: normal
    - family: BentonSans Medium
      fonts:
        - asset: assets/fonts/BentonSans-Medium.otf
          style: normal
    - family: BentonSans Bold
      fonts:
        - asset: assets/fonts/BentonSans-Bold.otf
          style: normal
    - family: BentonSans-Regular
      fonts:
        - asset: assets/fonts/BentonSans-Regular.otf
          style: normal
    - family: BentonSans Book
      fonts:
            - asset: assets/fonts/BentonSans-Book.otf
              style: normal
