name: food_delivery
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  flutter_typeahead: ^4.0.0
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.1.1
  custom_navigator: ^0.3.0
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Viga
      fonts:
        - asset: assets/fonts/Viga-Regular.ttf
          style: normal
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          style: normal
    - family: BentonSans Medium
      fonts:
        - asset: assets/fonts/BentonSans-Medium.otf
          style: normal
    - family: BentonSans Bold
      fonts:
        - asset: assets/fonts/BentonSans-Bold.otf
          style: normal
    - family: BentonSans-Regular
      fonts:
        - asset: assets/fonts/BentonSans-Regular.otf
          style: normal
    - family: BentonSans Book
      fonts:
            - asset: assets/fonts/BentonSans-Book.otf
              style: normal
